require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
  - db/schema.rb
  - vendor/**/*
  - bin/*
  - node_modules/**/*
  - spec/**/*
  - Gemfile

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 17

Style/YodaCondition:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
